:root{--bg:#070a11;--panel:#111827;--panel2:#182235;--line:#2d3a50;--text:#eef5ff;--muted:#98a8bc;--cyan:#25d9ff;--orange:#ff9c2b;--danger:#ff6b7a}
*{box-sizing:border-box}html{color-scheme:dark}body{margin:0;background:linear-gradient(145deg,#05070c,#111a2b);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans JP",sans-serif;min-height:100vh}
button,input,select{font:inherit}.topbar{position:sticky;top:0;z-index:20;padding:14px;background:rgba(7,10,17,.96);border-bottom:1px solid var(--line);backdrop-filter:blur(10px)}
.topbar-inner{display:flex;justify-content:space-between;align-items:center;gap:12px;max-width:1180px;margin:auto}.topbar h1{font-size:19px;margin:0;color:var(--cyan);letter-spacing:.04em}.subtitle{margin:4px 0 0;color:var(--muted);font-size:12px}
.mode-tabs{display:flex;gap:7px}.controls{display:grid;grid-template-columns:minmax(180px,2fr) repeat(6,minmax(120px,1fr));gap:8px;max-width:1180px;margin:12px auto 0}
button,input,select{min-height:42px;padding:9px 10px;border:1px solid #35455e;border-radius:8px;background:#111a29;color:var(--text)}button{cursor:pointer;font-weight:700}button:hover{border-color:var(--cyan)}.mode.active{background:#073c4b;border-color:var(--cyan)}.danger{border-color:#63303a}.danger:hover{border-color:var(--danger)}
.status{max-width:1180px;margin:9px auto 0;color:var(--muted);font-size:13px;line-height:1.45}.status.error{color:#ff9caa}main{max-width:1180px;margin:auto;padding:14px}.summary{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.badge{padding:6px 10px;border:1px solid var(--line);border-radius:999px;background:var(--panel);font-size:12px}
.group{margin-bottom:10px;border:1px solid var(--line);border-radius:10px;overflow:hidden;background:var(--panel)}.group-title{width:100%;display:flex;justify-content:space-between;border:0;border-radius:0;background:linear-gradient(90deg,#182235,#101725);padding:12px 14px}.group-title strong{color:var(--orange)}.group.closed .rows{display:none}
.row{display:grid;grid-template-columns:64px minmax(230px,1fr) 150px;gap:10px;align-items:center;padding:9px 12px;border-top:1px solid #202c40}.row:hover{background:#152033}.ver{color:var(--muted);font-size:12px}.title{font-weight:650;overflow-wrap:anywhere}.option-select{width:100%}.empty{text-align:center;padding:60px 10px;color:var(--muted)}small{color:var(--muted)}
@media(max-width:900px){.controls{grid-template-columns:1fr 1fr}.controls input{grid-column:1/-1}}
@media(max-width:620px){.topbar-inner{align-items:flex-start;flex-direction:column}.mode-tabs{width:100%}.mode{flex:1}.row{grid-template-columns:42px minmax(0,1fr) 112px;padding:9px 8px;gap:7px}.topbar h1{font-size:16px}.subtitle{display:none}}
